Santa-Clara-Imaginarium-Lab/human-ai

client/index.html
client/src/components/login/Login.css
client/src/components/login/Login.jsx
client/src/index.css

- Added yellow background to Login Page
- Changed placeholder text to "Enter your participant ID"
- Added note to help users find participant ID
- Added Jaro, Jaldi, and Jockey One fonts
- index.css was originally changed then reverted

Login Page

---

client/src/components/gametutorial/GameTutorial.css
client/src/components/gametutorial/GameTutorial.jsx
client/src/components/gametutorial/constants.js
client/src/index.css

1. updated the GameTutorial.jsx and GameTutorial.css file. Now the user can see what is Cooperate and Defect and the points.

Decision tutorial

---

client/src/components/game/Game.jsx
client/src/components/login/Login.jsx
client/src/components/questions/Qualtrix.css
client/src/components/questions/Qualtrix.jsx
client/src/components/questions/Question.css
client/src/components/questions/Question.jsx
client/src/components/questions/constants.js
client/src/components/survey/Survey.css
client/src/components/survey/Survey.jsx
client/src/components/welcome/Welcome.jsx
client/src/main.jsx

1.) Added questions
2.) CSS styling
3.) Order of pages

Sample survey

---

client/src/components/chatbotTutorial/ChatbotTutorial.css
client/src/components/chatbotTutorial/DemoChat.css
client/src/components/game/Game.css
client/src/components/game/Game.jsx
client/src/components/gametutorial/GameTutorial.css
client/src/components/gametutorial/GameTutorial.jsx
client/src/components/login/Login.jsx
client/src/components/questions/Question.css
client/src/components/survey/Survey.css
client/src/components/tutorial/Tutorial.css
client/src/components/welcome/Welcome.css
client/src/components/welcome/Welcome.jsx
client/src/index.css
client/src/routes/chatPage/chatPage.css

It should be completely ready for the UX study

Polish for ux

---

client/src/components/chatbotTutorial/DemoChat.jsx
client/src/components/questions/constants.js
client/vite.config.js

All our fixes, with love. <3
Solution to make “Exit” to game phase more clear to participants
- Changed button label from“Exit” to “Continue”
- Changed corresponding tooltip from “Finish chatting” to “Start decision phase”
Decision choices of AI and participant larger during game phase for visibility
- Show points earned after every decision
Understanding and visibility of chatbot tooltips
- “Press any key to continue” changed for a activate button or disregard completely and chat is activated automatically when user enters
- Add bubble to exit button to explain that is how to exit chat and go back to game 
- Added hover feature to exit and send buttons, no need for message to be displayed now because tutorial explains its functionality,

UX Fixes From Winter Break

---

client/src/components/login/Login.jsx
client/src/components/newPrompt/NewPrompt.jsx
client/src/components/newPrompt/newPrompt.css
client/src/components/welcome/Welcome.css
client/src/components/welcome/Welcome.jsx
client/src/main.jsx
client/src/routes/chatPage/ChatPage.jsx
client/src/routes/dashboardPage/DashboardPage.jsx

First draft of personality prompted bots.
You can switch between the different personalities using a text input similar to the color codes from the UX study. Personality will persist throughout the session.
Additionally, upon hitting exit, the bot will respond to a [SYSTEM] message to give its response to the current prisoner's dilemma round.
Please test the current prompts and provide feedback when you can! In general, you'll find the prompts shorter than before due to the line `Respond with a length mirroring the user's sentence length.`

Personality prompts

---

client/src/components/questions/Question.jsx
client/src/components/tutorial/Tutorial.jsx
client/src/constants/personalities.jsx
client/src/routes/dashboardPage/DashboardPage.jsx

-Bot personalities now go in a random order
-After the 5th bot/personality, the site goes to the End Screen

Random Order of Bots

---

client/src/components/game/Game.jsx
client/src/main.jsx
client/src/routes/endScreen/EndScreen.jsx
client/src/routes/endScreen/endScreen.css

-Implemented a part of @MeguKanzawa's design for the End Screen
-Connected real chatbot and user scores to the End Screen
-Added absolute positioning to chatbot and user scores to avoid weird positioning

End Screen

---

client/src/components/game/Game.jsx
client/src/components/questions/Question.jsx
client/src/components/questions/constants.js
client/src/components/tutorial/Tutorial.jsx

Game now just becomes 1 randomly generated chatbot.
Additional fixes in this PR include importing the rest of the qualtrix questions and force-resetting "gameLog" sessionStorage entries every time the tutorial starts

Reduce rounds

---

client/src/components/game/Game.jsx
client/src/components/login/Login.jsx
client/src/components/tutorial/Tutorial.jsx
client/src/components/welcome/Welcome.css
client/src/components/welcome/Welcome.jsx
client/src/main.jsx
client/src/routes/dashboardPage/DashboardPage.jsx

Official "admin panel" (without password yet)
Safety resets throughout the game
isResearchMode boolean to eventually toggle certain types of saving data
Accumulating points during the rounds of the decision phase

Reorganize settings

---

client/src/components/game/Game.css
client/src/components/game/Game.jsx

Help button!

---

client/src/components/gametutorial/GameTutorial.css
client/src/components/gametutorial/GameTutorial.jsx

-New proceed to chat button in tutorial to match game play. 
-Removed old proceed button.

Proceed in Tutorial

---

client/src/components/aiPretest/AiPretest.css
client/src/components/aiPretest/AiPretest.jsx
client/src/components/brief/Brief.css
client/src/components/brief/Brief.jsx
client/src/components/chatbotTutorial/DemoChat.jsx
client/src/components/consentForm/ConsentForm.css
client/src/components/consentForm/ConsentForm.jsx
client/src/components/demographicQuestions/DemographicQuestions.css
client/src/components/demographicQuestions/DemographicQuestions.jsx
client/src/components/login/Login.jsx
client/src/components/personalityQuestions/PersonalityQuestions.css
client/src/components/personalityQuestions/PersonalityQuestions.jsx
client/src/components/pregame/Pregame.css
client/src/components/pregame/Pregame.jsx
client/src/main.jsx

add new pages before tutorial + new pregame pages

---

backend/index.js
backend/models/gameScores.js
backend/models/surveyQuestions.js
client/src/components/questions/Question.jsx
client/src/components/survey/Survey.jsx
client/src/routes/dashboardPage/DashboardPage.jsx

1. Fixed issue in chats database: new chat was created for the same user logging in at different times
2. Game scores: added database support
3. Survey responses: added database support

Backend database updates

---

client/src/components/game/Game.jsx
client/src/components/survey/Survey.jsx
client/src/components/tutorial/Tutorial.jsx
client/src/constants/formattedPersonalities.jsx
client/src/routes/endScreen/EndScreen.jsx
client/src/routes/endScreen/endScreen.css

- This End Screen supports the 5-round game, **not** the up-to-5-round game
- Removed the 4 other chatbot archetypes from the End Screen
- Implemented new End Screen design

New End Screen

---

backend/index.js
client/src/components/login/Login.jsx

While logging in with a user ID, the database is queried to check whether the ID has been used already. Error msg is displayed and login with that ID is not allowed if true.

Query db to check if a user ID as been used already

---

client/src/components/game/Game.jsx
client/src/components/tutorial/Tutorial.jsx
client/src/routes/endScreen/EndScreen.jsx

Extremely simple change (just 2 lines of code), but I still request a review because the new range of rounds (2-5) BREAKS #58 END SCREEN V2

Randomize rounds at the beginning

---

client/src/components/chatbotArchetype/ChatbotArchetype.css
client/src/components/chatbotTutorial/DemoChat.css
client/src/components/chatbotTutorial/DemoChat.jsx
client/src/components/debrief/Debrief.css
client/src/components/game/Game.css
client/src/components/game/Game.jsx
client/src/components/gametutorial/GameTutorial.css
client/src/components/gametutorial/GameTutorial.jsx
client/src/components/gametutorial/constants.js
client/src/components/login/Login.jsx
client/src/components/welcome/Welcome.css
client/src/components/welcome/Welcome.jsx
client/src/routes/endScreen/EndScreen.jsx

New tutorial, with improved clarity and interactivity. Additonally, a new "objective prompt" is present in many pages, complete with a flashy bounce animation.
There is 1500 (1.5s) wait time between each prompt in the Game Tutorial - this can be changed locally during development to speed through it faster.
_**WARNING: I ACCIDENTALLY DID A MERGE MAIN INTO THIS BRANCH, AND THEN COMMITTED NO CHANGES, MESSING UP THE GIT HISTORY. THERE WILL PROBABLY BE CONFLICTS FOR LATER BRANCHES - I'M SO SORRY**_

Tutorial revamp

---

client/src/components/badEnding/BadEnding.css
client/src/components/badEnding/BadEnding.jsx
client/src/components/consentForm/ConsentForm.css
client/src/components/consentForm/ConsentForm.jsx
client/src/main.jsx

Updated Stuff for Eathan

---

client/src/components/AILiteracy/AiLiteracy.css
client/src/components/AILiteracy/PreApply.jsx
client/src/components/AILiteracy/PreUnderstanding.jsx
client/src/components/AIProblemSolving/PreEfficacy.jsx
client/src/components/AISelfCompetency/PrePersuassion.jsx
client/src/components/TrustPeopleAutomation/PreTPA.jsx
client/src/components/TrustPeopleAutomation/PreTPA2.jsx
client/src/components/TrustScaleExplainableAI/PreTXAI.jsx
client/src/components/TrustScaleExplainableAI/PreTXAI2.jsx
client/src/components/demographicQuestions/DemographicQuestions.css
client/src/components/game/Game.css
client/src/components/gametutorial/GameTutorial.jsx
client/src/routes/endScreen/endScreen.css

Fixed the popup menu for "?" button on Game.jsx, made end screen responsive, pre survey screen question boxes are of even sizes.

Responsive design

---

backend/index.js
backend/models/postGameFreeResponse.js
backend/package.json
client/src/components/freeResponse/PostGameFreeResponse.css
client/src/components/freeResponse/PostGameFreeResponse.jsx
client/src/components/freeResponse/PostGameFreeResponseConstants.js
client/src/components/questions/Question.jsx
client/src/main.jsx

Added free response questions after game.

Post game frq

---

client/src/components/chatbotTutorial/DemoChat.css
client/src/components/chatbotTutorial/DemoChat.jsx
client/src/components/game/Game.css
client/src/components/game/Game.jsx
client/src/components/gametutorial/GameTutorial.css
client/src/components/gametutorial/GameTutorial.jsx
client/src/components/gametutorial/constants.js
client/src/components/login/Login.jsx
client/src/components/welcome/Welcome.jsx

- Moved "Share" and "Withhold" buttons to the left and right of the diamond
- Moved "Go to Chat" button to the bottom left
- Moved "Lock In" button to the bottom right
- Added Scoreboard at the bottom of the page
- Increased size of all buttons
- Moved error message

Game Page Revamp

---

client/src/components/chatbotTutorial/DemoChat.css
client/src/components/chatbotTutorial/DemoChat.jsx
client/src/components/consentForm/ConsentForm.jsx
client/src/components/game/Game.jsx
client/src/components/gametutorial/GameTutorial.css
client/src/components/gametutorial/GameTutorial.jsx
client/src/routes/endScreen/EndScreen.jsx

Last adjustments from Erin and others on how to make the tutorial more user-friendly

Final flow adjustments

---

client/src/components/game/Game.jsx

Make "?" help text have blue highlighting (same accent as tutorial tooltips) and have text that aligns closer to the Game Tutorial
Lillian's work!

L (Colored Help Page)

---

backend/index.js
client/package.json
client/src/components/complete/Complete.jsx
client/src/components/debrief/Debrief.jsx
client/src/components/gameEndCode/GameEndCode.css
client/src/components/gameEndCode/GameEndCode.jsx
client/src/main.jsx

New code will be generated daily in the timeframe 12AM-1AM PDT -> Trigger for this code is added in Google sheets
This code will be fetched from the database and displayed at the end of the game (/complete page).

Game completion code
